name: GSMArena Releases Tracker

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

concurrency: 
  group: gsmarena-releases-tracker
  cancel-in-progress: false

jobs:
  track:
    name: Track
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Setup Go Environment
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Install pup
        run: go install github.com/ericchiang/pup@latest
      - name: Run tracker.sh
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: ./gsmarena/release/tracker.sh
