name: LineageOS Devices Tracker Full Check

on:
  schedule:
    - cron: '0 12,18 * * *'
  workflow_dispatch:

concurrency: 
  group: lineageos-devices-tracker
  cancel-in-progress: false

jobs:
  track:
    name: Track
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run tracker.sh
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: ./lineageos/devices/tracker.sh full
