name: Magisk Modules Tracker

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

concurrency: 
  group: magisk-modules-tracker
  cancel-in-progress: false

jobs:
  track:
    name: Track
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Run tracker.sh
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: ./magisk/modules/tracker.sh
